version: '3'

services:
  # Nginx
  nginx:
    container_name: nginx
    build: ./requirements/nginx/
    restart: always
    ports:
      - 443:443
    volumes:
      - wordpress_v:/var/www/wordpress
    networks:
      - inception
  # Database
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    restart: always
    volumes:
      - mysql_v:/var/lib/mysql
    env_file:
      - ./.env
    networks:
      - inception
  # Wordpress
  wordpress:
    container_name: wordpress
    depends_on:
      - mariadb
    build: ./requirements/wordPress
    restart: always
    volumes:
      - wordpress_v:/var/www/wordpress
    env_file:
      - ./.env
    networks:
      - inception
  # Bonus Part
  # Redis
  redis:
    container_name: redis
    depends_on:
      - wordpress
    build: ./requirements/bonus/redis
    restart: always
    volumes:
      - wordpress_v:/var/www/wordpress
    networks:
      - inception
  # FTP server
  ftp:
    container_name: ftp
    depends_on:
      - wordpress
    build: ./requirements/bonus/ftp
    restart: always
    volumes:
      - wordpress_v:/home/fury/mysite
    env_file:
      - ./.env
    ports:
      - 21:21
    networks:
      - inception
  # portfolio
  portfolio:
    container_name: portfolio
    build: ./requirements/bonus/website
    restart: always
    ports:
      - 80:80
    networks:
      - inception
  # Adminer
  adminer:
    container_name: adminer
    build: ./requirements/bonus/adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - inception
  cadvisor:
    container_name: cadvisor
    build: ./requirements/bonus/cadvisor
    restart: always
    ports:
      - 9090:8080
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker:/var/lib/docker:ro
    networks:
      - inception
# Volumes
volumes:
  mysql_v:
    name: mysql_v
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/abdeel-o/data/mysql

  wordpress_v:
    name: wordpress_v
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/abdeel-o/data/wordpress
# Network
networks:
  inception:
    driver: bridge