version: '3'

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx/
    restart: always
    ports:
      - 443:443
    volumes:
      - wp_files:/var/www/html
    networks:
      - inception
  # Database
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    restart: always
    volumes:
      - wp_database:/var/lib/mysql
    env_file:
      - ./.env
    networks:
      - inception
    # Wordpress
  wordpress:
    container_name: wordpress
    depends_on:
      - mariadb
    build: ./requirements/wordPress
    restart: always
    volumes:
      - wp_files:/var/www/wordpress
    env_file:
      - ./.env
    networks:
      - inception
# Volumes
volumes:
  wp_database:
    name: wp_database
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/abdeel-o/data/wp_database

  wp_files:
    name: wp_files
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/abdeel-o/data/wp_files
# Network
networks:
  inception:
    driver: bridge
